### ISSUE TITLE
Doesn't open a Steam login page.

### ISSUE THREAD

**Issue by saintnoodle** [dzdevteam/mod_steamlogin#1]
Module doesn't go past 'OpenID Transaction in Progress' message and doesn't allow a login.

**Comment by lephuongbg** [comment]
Hi @saintnoodle, this module can not work by itself. It needs [com_steamid](https://github.com/dzdevteam/com_steamid), [plg_authentication_steamid](https://github.com/dzdevteam/plg_authentication_steamid) and [lib_openid](https://github.com/dzdevteam/lib_openid).
Please feedback if you have any further problem.

**Comment by saintnoodle** [comment]
I used all these together. I'll try it again and see if it works.

**Comment by saintnoodle** [comment]
Tested again, with all four extensions installed, it doesn't redirect or open a steam login page and sticks on the transaction message.

http://i.imgur.com/YHaN3Bc.png

Is there anything I could be doing wrong or anything you could help with.
the webpage is http://noodle.noip.me/

**Comment by lephuongbg** [comment]
Can you tell me what is the error message in the web console?

**Comment by saintnoodle** [comment]
I don't think bitnami comes with a console.

**Comment by saintnoodle** [comment]
if you can let me know of a way to access a console either to do with joomla or php then let me know but I've added the steam button back in the top right if you want to test yourself.

**Comment by saintnoodle** [comment]
I have accessed the log file and the error appears to be with the OpenID library. It is activated. I'll copy and paste the code in a minute.

**Comment by saintnoodle** [comment]
[Mon Oct 19 01:46:29.594000 2015] [:error] [pid 9348:tid 908] [client 92.1.11.140:64995] PHP Fatal error:  Define Auth_OpenID_RAND_SOURCE as null to  continue with an insecure random number generator. in C:\Bitnami\joomla\apps\joomla\htdocs\libraries\openid\Auth\OpenID\CryptUtil.php on line 52, referer: http://noodle.noip.me/
[Mon Oct 19 02:07:55.563000 2015] [:error] [pid 9348:tid 884] [client 92.1.11.140:65310] PHP Fatal error:  Define Auth_OpenID_RAND_SOURCE as null to  continue with an insecure random number generator. in C:\Bitnami\joomla\apps\joomla\htdocs\libraries\openid\Auth\OpenID\CryptUtil.php on line 52, referer: http://noodle.noip.me/

**Comment by lephuongbg** [comment]
Please see this line (https://github.com/dzdevteam/lib_openid/blob/master/Auth/OpenID/CryptUtil.php#L23):

```
define('Auth_OpenID_RAND_SOURCE', '/dev/urandom');
```

Because you're on Windows, `/dev/urandom` is not available. You can replace that with `null` so that the library will continue to work.

**Comment by saintnoodle** [comment]
That's fixed the steam login issue but now I have a problem with authorisation. I'll assume that's to do with Joomla's global settings and edit them. I'll report if I have any more issues but if you come back and this is all you see, close the case. I appreciate your help and I'm glad you helped because I was losing all hope on adding the ability to login with steam.

**Comment by lephuongbg** [comment]
@saintnoodle you're welcome. You can open a question anytime you need.

**Comment by saintnoodle** [comment]
I can't seem to make authentication happy.

'LDAP can't have blank password'

Is that to do with the shuffle command in the steamID authentication php?

Also is there anyway I can contact you personally using IM?

[Mon Oct 19 10:37:40.655000 2015] [:error] [pid 9348:tid 956] [client 62.255.48.34:50574] Got no response code when fetching https://steamcommunity.com/openid/login, referer: http://noodle.noip.me/index.php/component/steamid/login?janrain_nonce=2015-10-19T08%3A55%3A23ZcPnC3K&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Flogin&openid.claimed_id=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561198035489833&openid.identity=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561198035489833&openid.return_to=http%3A%2F%2Fnoodle.noip.me%2Findex.php%2Fcomponent%2Fsteamid%2Flogin%3Fjanrain_nonce%3D2015-10-19T08%253A55%253A23ZcPnC3K&openid.response_nonce=2015-10-19T08%3A55%3A11Zxzvy25CSIDlXQSLp5td0NyuztdA%3D&openid.assoc_handle=1234567890&openid.signed=signed%2Cop_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle&openid.sig=QRVOMmbabmA19G%2FofQWzszXl7aY%3D
[Mon Oct 19 10:37:40.655000 2015] [:error] [pid 9348:tid 956] [client 62.255.48.34:50574] CURL error (60): SSL certificate problem: unable to get local issuer certificate, referer: http://noodle.noip.me/index.php/component/steamid/login?janrain_nonce=2015-10-19T08%3A55%3A23ZcPnC3K&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Flogin&openid.claimed_id=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561198035489833&openid.identity=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561198035489833&openid.return_to=http%3A%2F%2Fnoodle.noip.me%2Findex.php%2Fcomponent%2Fsteamid%2Flogin%3Fjanrain_nonce%3D2015-10-19T08%253A55%253A23ZcPnC3K&openid.response_nonce=2015-10-19T08%3A55%3A11Zxzvy25CSIDlXQSLp5td0NyuztdA%3D&openid.assoc_handle=1234567890&openid.signed=signed%2Cop_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle&openid.sig=QRVOMmbabmA19G%2FofQWzszXl7aY%3D
[Mon Oct 19 10:37:44.595000 2015] [:error] [pid 9348:tid 956] [client 62.255.48.34:50574] Got no response code when fetching https://steamcommunity.com/openid/login
[Mon Oct 19 10:37:44.595000 2015] [:error] [pid 9348:tid 956] [client 62.255.48.34:50574] CURL error (60): SSL certificate problem: unable to get local issuer certificate
[Mon Oct 19 10:37:44.598000 2015] [:error] [pid 9348:tid 956] [client 62.255.48.34:50574] PHP Notice:  Undefined index: username in C:\Bitnami\joomla\apps\joomla\htdocs\plugins\authentication\gmail\gmail.php on line 47
[Mon Oct 19 10:37:44.598000 2015] [:error] [pid 9348:tid 956] [client 62.255.48.34:50574] PHP Notice:  Undefined index: password in C:\Bitnami\joomla\apps\joomla\htdocs\plugins\authentication\ldap\ldap.php on line 40
[Mon Oct 19 10:37:44.598000 2015] [:error] [pid 9348:tid 956] [client 62.255.48.34:50574] PHP Notice:  Undefined index: username in C:\Bitnami\joomla\apps\joomla\htdocs\libraries\joomla\user\authentication.php on line 300
[Mon Oct 19 10:37:44.598000 2015] [:error] [pid 9348:tid 956] [client 62.255.48.34:50574] PHP Notice:  Undefined index: username in C:\Bitnami\joomla\apps\joomla\htdocs\libraries\joomla\user\authentication.php on line 305

**Comment by lephuongbg** [comment]
It said there was problem with SSL and LDAP authentication. 
1. Does your PHP have Curl and Open SSL extensions support?
2. Please disable Joomla's LDAP authentication plugin.

**Comment by saintnoodle** [comment]
I'll have a look in an hours time and report back if I need any further
assistance.

**Comment by saintnoodle** [comment]
Curl and open SSL are enabled and i have disabled LDAP and I now get 'Failed to authenticate: User is blacklisted.' with the same error messages as before. No user has been created with the steam ID so I don't know how this is possible.

**Comment by saintnoodle** [comment]
Now I'm getting the empty password message once again but it's nothing to do with ldap this time. Still same error.

**Comment by lephuongbg** [comment]
Are there messages in PHP log after you get that empty-password-error again? What is the version of your Joomla?

**Comment by lephuongbg** [comment]
Besides, inside administrator/index.php?option=com_steamid, do you see any entry created after you "logged in" from Steam? If you do not see any, I doubt that the steam authentication plugin is not enabled (Plugin needs to be enabled manually after installation).

**Comment by saintnoodle** [comment]
I'm using joomla 3.4.4. SteamID authentication plugin is enabled and the php log reaches the same errors as the apache logs. Should I use an earlier version of joomla 3?

**Comment by lephuongbg** [comment]
What did the log say? My project does use the latest version of joomla so that may not be the problem.

**Comment by saintnoodle** [comment]
[20-Oct-2015 01:43:00 America/Los_Angeles] Got no response code when fetching https://steamcommunity.com/openid/login

[20-Oct-2015 01:43:00 America/Los_Angeles] CURL error (60): SSL certificate problem: unable to get local issuer certificate

[20-Oct-2015 01:43:00 America/Los_Angeles] PHP Notice:  Undefined index: username in C:\Bitnami\joomla\apps\joomla\htdocs\libraries\joomla\user\authentication.php on line 300

[20-Oct-2015 01:43:00 America/Los_Angeles] PHP Notice:  Undefined index: username in C:\Bitnami\joomla\apps\joomla\htdocs\libraries\joomla\user\authentication.php on line 305

**Comment by saintnoodle** [comment]
could it still be an error with windows?

**Comment by lephuongbg** [comment]
Please try this:
http://stackoverflow.com/questions/30974869/how-to-solve-curl-error-60-ssl-certificate-in-laravel-5-while-facebook-authenti

**Comment by saintnoodle** [comment]
You can't access the private section of this site.

×
success

You have successfully logged in through Steam

**Comment by saintnoodle** [comment]
it worked but i've probably not got my permissions set up properly

Do you know why it's saying this because normal logging in worked before.

**Comment by lephuongbg** [comment]
Loging in using Steam will automatically create a new user if the Steam ID doesn't exist. If you want your steam id to be connected to your current account, you can edit the connection inside Steam ID component (in back-end).
Glad that this finally works for you.

**Comment by saintnoodle** [comment]
how do you make the steam id's automatically publish?

**Comment by lephuongbg** [comment]
It doesn't matter to be published or not. You do not have to care about that :)

**Comment by saintnoodle** [comment]
My steam id was unpublished and it was giving me the private error but i published it and it let me log in

**Comment by lephuongbg** [comment]
The steam id should not have relation to the private error. The error is because you did not set the correct permission for associated user of that steam id. 
At least now I think your problem is solved.
