### ISSUE TITLE
I get Error 500 after click on button login.

### ISSUE THREAD

**Issue by Orsey** [dzdevteam/mod_steamlogin#2]
I am using Joomla 3.7.3
I am installed:
- com_steamid
- mod_steamlogin
- plg_authentication_steamid (and enable this)
- lib_openid

I am publish module steamlogin on my test site and click button login and get error 500 in console /*screen*/

Help me!!! How I can fix it???

![image](https://user-images.githubusercontent.com/2915062/27971822-c54d6282-635c-11e7-8d64-015e96a82751.png)

**Comment by lephuongbg** [comment]
Could you show the specific error message?

**Comment by Orsey** [comment]
Where I can see this is specific error message?
On page after ckick "Login" I get this /*screen*/ and nothing anymore (

![image](https://user-images.githubusercontent.com/2915062/27972162-0197ac9c-635e-11e7-8f78-1ebadac763b6.png)

**Comment by lephuongbg** [comment]
In the network tab of chrome console, please click on the request that have 500 status code and send me screenshot again.

**Comment by Orsey** [comment]
All for you )
![image](https://user-images.githubusercontent.com/2915062/27972369-ce870f36-635e-11e7-9c5d-7a158e25742f.png)

**Comment by lephuongbg** [comment]
Could you choose "Preview" tab and send another screenshot?

**Comment by Orsey** [comment]
this clear (
![image](https://user-images.githubusercontent.com/2915062/27972563-7bd848e4-635f-11e7-80f3-6497c66a855c.png)

**Comment by lephuongbg** [comment]
Well, could you get any error message from your server log? It will depend on how you set up your server to locate the file.

**Comment by Orsey** [comment]
just a moment, i try do this

**Comment by Orsey** [comment]
![image](https://user-images.githubusercontent.com/2915062/27973310-49646e8a-6362-11e7-9684-0cebf89965ff.png)

**Comment by Orsey** [comment]
I am tryed change version openid, I get new version from this page https://github.com/dzdevteam/lib_openid but after this I get the same result

**Comment by lephuongbg** [comment]
Are you happen to developing this under windows?

**Comment by Orsey** [comment]
I don't understande you. What "developing this under windows" you want to see? I am from Ukraine and my English not good (

**Comment by lephuongbg** [comment]
Sorry for not being clear. Is your operating system Microsoft Windows?
As Windows doesn't have **/dev/urandom**,  you will need to change some source code in **lib_openid/Auth/OpenID/CryptUtil.php**:

    define('Auth_OpenID_RAND_SOURCE', '/dev/urandom');

To:

    define('Auth_OpenID_RAND_SOURCE', null);

**Comment by Orsey** [comment]
Operation system of server is Linux, not Windows.
Yeeeesssss ))) I am logged )
I must write about this component + module + plugin on my blog ) Very, very, very thanks!!!

**Comment by Orsey** [comment]
I close it now )

**Comment by lephuongbg** [comment]
Glad you have it solved. Though an advise is that you should use a random source specific to your operating system. Most linux systems does have /dev/urandom available so either we have permission error or you will need to check which random source is available for your specific case.

**Comment by Orsey** [comment]
I am understand. I will write about this on my blog. Thank you very match!
